sudo: false
language: node_js
node_js:
  - "stable"
  - "6"
  - "5.5"
script:
  - "npm run test:only"
  - "npm run ci"
before_install:
  - npm install -g grunt-cli
cache:
  directories:
    - node_modules
